#pragma once
#define MAX_DAY_IN_MONTH 31
#define MIN_DAY_IN_MONTH 1
#define MAX_MONTH_IN_YEAR 12
#define MIN_MONTH_IN_YEAR 1
#define MAX_YEAR 2100
#define MIN_YEAR 1900
#define MAX_MINUTE_IN_HOUR 59
#define MIN_MINUTE_IN_HOUR 0
#define MAX_HOUR_IN_DAY 23
#define MIN_HOUR_IN_DAY 0
#define ADD_0_TO_MINUTE 10
#define EXIT_NUMBER 67